### Baseline_Model

In [3]:
import pandas as pd 
import fastf1
fastf1.Cache.enable_cache('f1_cache')
df_2023 = pd.read_csv("final_merged_2023_data.csv")
df_2023.head(5)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_11488\789486041.py:4: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv("final_merged_2023_data.csv")

,Driver,DriverNumber,LapNumber,Stint,Compound,TyreLife,FreshTyre,LapTime,Sector1Time,Sector2Time,...,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed,RoundNumber,Session,Date,GP
0,ALB,23,3,2,MEDIUM,3,0,96.216,30.470,41.812,...,12.0,1017.2,False,41.1,10.0,2.2,1.0,FP1,05-03-2023,Bahrain Grand Prix
1,ALB,23,4,2,MEDIUM,4,0,137.050,42.034,63.859,...,12.0,1017.4,False,41.1,341.0,2.5,1.0,FP1,05-03-2023,Bahrain Grand Prix
2,ALB,23,5,2,MEDIUM,5,0,97.024,31.111,41.787,...,13.0,1017.4,False,41.0,342.0,2.5,1.0,FP1,05-03-2023,Bahrain Grand Prix
3,ALB,23,6,2,MEDIUM,6,0,126.270,37.960,52.041,...,13.0,1017.4,False,40.9,342.0,2.0,1.0,FP1,05-03-2023,Bahrain Grand Prix
4,ALB,23,8,3,MEDIUM,8,0,96.859,30.984,41.838,...,13.0,1017.2,False,40.8,344.0,3.5,1.0,FP1,05-03-2023,Bahrain Grand Prix

In [4]:
stints_clean = pd.read_csv('stints_clean.csv')
stints_clean.head(5)

                      GP Driver  Stint Compound  StintLength
0  Australian Grand Prix    ALB      1   MEDIUM            6
1  Australian Grand Prix    ALO      1   MEDIUM            8
2  Australian Grand Prix    ALO      2     HARD           46
3  Australian Grand Prix    BOT      1     SOFT            1
4  Australian Grand Prix    BOT      2     HARD            6

In [7]:
model_df = stints_clean[
    (stints_clean['GP'] != 'Qatar Grand Prix') & 
    (stints_clean['Compound'].isin(['SOFT', 'MEDIUM', 'HARD']))
].copy()
model_df.head(5)

                      GP Driver  Stint Compound  StintLength
0  Australian Grand Prix    ALB      1   MEDIUM            6
1  Australian Grand Prix    ALO      1   MEDIUM            8
2  Australian Grand Prix    ALO      2     HARD           46
3  Australian Grand Prix    BOT      1     SOFT            1
4  Australian Grand Prix    BOT      2     HARD            6

In [ ]:
# Checking for NaN values in the target variable
model_df['StintLength'].isna().any()

False

In [ ]:
#Defining features and target variable
X = model_df[['GP', 'Compound']]
Y = model_df['StintLength']